"""criando tabela boxes

Revision ID: 0a68038ff0a1
Revises: 
Create Date: 2022-04-28 17:21:51.399788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0a68038ff0a1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boxes",
        sa.Column("flag", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("monthly_price", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("flag"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("boxes")
    # ### end Alembic commands ###
