"""criando tabela clients

Revision ID: 1e2a882777ba
Revises: 0a68038ff0a1
Create Date: 2022-04-28 17:22:37.351955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1e2a882777ba"
down_revision = "0a68038ff0a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cpf", sa.String(length=11), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("total_points", sa.Integer(), nullable=True),
        sa.Column("box_flag", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["box_flag"],
            ["boxes.flag"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cpf"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("clients")
    # ### end Alembic commands ###
