"""Cascade deletion of client

Revision ID: 56ee3ca77f0d
Revises: a5475f1bb14e
Create Date: 2022-05-05 10:54:03.817328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ee3ca77f0d'
down_revision = 'a5475f1bb14e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_orders_client_id_fkey', 'client_orders', type_='foreignkey')
    op.create_foreign_key(None, 'client_orders', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_orders', type_='foreignkey')
    op.create_foreign_key('client_orders_client_id_fkey', 'client_orders', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###
