"""criando tabela orders

Revision ID: 640fef8bc444
Revises: 9881371e0ab2
Create Date: 2022-04-29 17:18:07.684537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640fef8bc444'
down_revision = '9881371e0ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
