"""criando tabela clients

Revision ID: 6ac5c61ee45f
Revises: d1139234845b
Create Date: 2022-04-29 13:38:47.537652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac5c61ee45f'
down_revision = 'd1139234845b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('box_flag', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['box_flag'], ['boxes.flag'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
