"""Cascade deletion of product

Revision ID: 898f95f52f44
Revises: 56ee3ca77f0d
Create Date: 2022-05-05 18:29:15.931191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "898f95f52f44"
down_revision = "56ee3ca77f0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "product_orders_product_id_fkey", "product_orders", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "product_orders", "products", ["product_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "product_orders", type_="foreignkey")
    op.create_foreign_key(
        "product_orders_product_id_fkey",
        "product_orders",
        "products",
        ["product_id"],
        ["id"],
    )
    # ### end Alembic commands ###
